sudo: false

language: php

notifications:
  on_success: never
  on_failure: change

php:
    - 5.3
    - 7.0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/force-email-login/
    - GH_REF: https://github.com/miya0001/force-email-login.git
    - secure: "WLOixP3JzXBFl9byFr5Bv4HpidAN6XKNdiBh9bBElF6ggSy/cpx4Q+Kdqq362OmyRXHIAw0vN06souw9tWSrtkE8hGCZ+OLIPt4jvk9+pYXJP7My2c1SHzKB2gnOaCSrAyRpBs1NKLYP9mqqmfmQn1N+iMtgB8bbmMM/FmY/mVE="

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit

after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
